spring:
  datasource:
    password: system
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    
  jpa:
    hibernate:
       ddl-auto: update
    show-sql: true

  config:
    activate:
      on-profile:
      - dev

server:
    port: 4085
    
---

spring:
  datasource:
    password:
    url: jdbc:h2:file:C:/h2data/sample
    username: system
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
  config:
    activate:
      on-profile:
      - test
server:
    port: 4024